//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contemplation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contemplation()
        {
            this.Pollution = new HashSet<Pollution>();
        }
    
        public long id_contemplation { get; set; }
        public Nullable<long> id_sample { get; set; }
        public Nullable<long> id_user { get; set; }
        public string type_contemplation { get; set; }
        public string result { get; set; }
        public Nullable<long> id_norm { get; set; }
    
        public virtual Norm Norm { get; set; }
        public virtual Sample Sample { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pollution> Pollution { get; set; }
    }
}
