//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public long id_event { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> data_time { get; set; }
        public Nullable<long> id_region { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
