//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long id_notification { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RowId { get; set; }
        public string ChangeType { get; set; }
        public Nullable<System.DateTime> Changet { get; set; }
    }
}
