//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization_Event
    {
        public long id_event_organiztion { get; set; }
        public Nullable<long> id_event { get; set; }
        public Nullable<long> id_organization { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
