//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pollution
    {
        public long id_pollution { get; set; }
        public Nullable<long> id_contemplation { get; set; }
        public Nullable<double> levels { get; set; }
        public Nullable<long> id_region { get; set; }
        public Nullable<System.DateTime> data_time { get; set; }
    
        public virtual Contemplation Contemplation { get; set; }
        public virtual Region Region { get; set; }
    }
}
