//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pollution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pollution()
        {
            this.Region_Pollution = new HashSet<Region_Pollution>();
        }
    
        public long id_pollution { get; set; }
        public Nullable<long> id_contemplation { get; set; }
        public string levels { get; set; }
        public string source { get; set; }
        public Nullable<System.DateTime> data_time { get; set; }
    
        public virtual Contemplation Contemplation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Region_Pollution> Region_Pollution { get; set; }
    }
}
