//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region_Pollution
    {
        public long id_region_pollution { get; set; }
        public Nullable<long> id_region { get; set; }
        public Nullable<long> id_pollution { get; set; }
    
        public virtual Pollution Pollution { get; set; }
        public virtual Region Region { get; set; }
    }
}
