/****** Object:  Database [GreanTrail]    Script Date: 13.06.2024 2:42:10 ******/
CREATE DATABASE [GreanTrail]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GreanTrail', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GreanTrail.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GreanTrail_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GreanTrail_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GreanTrail].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GreanTrail] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GreanTrail] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GreanTrail] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GreanTrail] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GreanTrail] SET ARITHABORT OFF 
GO

ALTER DATABASE [GreanTrail] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GreanTrail] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GreanTrail] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GreanTrail] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GreanTrail] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GreanTrail] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GreanTrail] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GreanTrail] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GreanTrail] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GreanTrail] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GreanTrail] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GreanTrail] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GreanTrail] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GreanTrail] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GreanTrail] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GreanTrail] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GreanTrail] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GreanTrail] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GreanTrail] SET  MULTI_USER 
GO

ALTER DATABASE [GreanTrail] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GreanTrail] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GreanTrail] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GreanTrail] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GreanTrail] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GreanTrail] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GreanTrail] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GreanTrail] SET  READ_WRITE 
GO


